# Generated by Django 6.0.6 on 2026-07-06 04:18

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('preferences', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('programs_offered', models.JSONField(default=list, help_text='e.g. ["B.Tech CSE", "B.Tech Mechanical", "MBA"]')),
                ('affiliation', models.CharField(blank=True, help_text='e.g. GTU, AICTE', max_length=150)),
                ('established_year', models.PositiveIntegerField(blank=True, null=True)),
                ('admission_process', models.TextField(blank=True)),
                ('fees_range_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fees_range_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('has_hostel', models.BooleanField(default=False)),
                ('has_mess', models.BooleanField(default=False)),
                ('fest_name', models.CharField(blank=True, max_length=150)),
                ('fest_month', models.CharField(blank=True, max_length=20)),
                ('website', models.URLField(blank=True)),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='colleges/')),
                ('average_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('popularity_score', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-popularity_score'],
                'indexes': [models.Index(fields=['city'], name='catalog_col_city_ae229c_idx'), models.Index(fields=['average_rating'], name='catalog_col_average_ed000a_idx')],
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('place_type', models.CharField(choices=[('RESTAURANT', 'Restaurant'), ('CAFE', 'Cafe'), ('STREET_FOOD', 'Street food stall'), ('TOURIST_SPOT', 'Tourist spot'), ('HOSTEL', 'Hostel'), ('PG', 'PG / paying-guest accommodation'), ('MESS', 'Mess / tiffin service'), ('OTHER', 'Other')], db_index=True, max_length=20)),
                ('description', models.TextField(blank=True)),
                ('address_line', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('pincode', models.CharField(blank=True, max_length=10)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('price_level', models.PositiveSmallIntegerField(default=2, help_text='1=cheap .. 4=premium, roughly matches budget_band', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('average_cost_for_two', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('popularity_score', models.PositiveIntegerField(default=0, help_text='rolling count of views/searches/orders, feeds ranking')),
                ('opens_at', models.TimeField(blank=True, null=True)),
                ('closes_at', models.TimeField(blank=True, null=True)),
                ('is_open_24h', models.BooleanField(default=False)),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='places/')),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False, help_text='admin-verified listing')),
                ('near_college', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nearby_places', to='catalog.college')),
            ],
            options={
                'ordering': ['-popularity_score'],
            },
        ),
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=150)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('is_vegetarian', models.BooleanField(default=True)),
                ('is_available', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='food/')),
                ('average_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('order_count', models.PositiveIntegerField(default=0, help_text='feeds popularity ranking')),
                ('category', models.ForeignKey(blank=True, limit_choices_to={'type': 'FOOD'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='food_items', to='preferences.preferencecategory')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_items', to='catalog.place')),
            ],
        ),
        migrations.AddIndex(
            model_name='place',
            index=models.Index(fields=['city', 'place_type'], name='catalog_pla_city_b648a2_idx'),
        ),
        migrations.AddIndex(
            model_name='place',
            index=models.Index(fields=['latitude', 'longitude'], name='catalog_pla_latitud_80c56d_idx'),
        ),
        migrations.AddIndex(
            model_name='place',
            index=models.Index(fields=['average_rating'], name='catalog_pla_average_f4f849_idx'),
        ),
        migrations.AddIndex(
            model_name='place',
            index=models.Index(fields=['popularity_score'], name='catalog_pla_popular_14c850_idx'),
        ),
        migrations.AddIndex(
            model_name='fooditem',
            index=models.Index(fields=['name'], name='catalog_foo_name_f220e4_idx'),
        ),
        migrations.AddIndex(
            model_name='fooditem',
            index=models.Index(fields=['place', 'is_available'], name='catalog_foo_place_i_b8b7db_idx'),
        ),
    ]
