# Generated by Django 6.0.6 on 2026-07-06 04:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PreferenceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('FOOD', 'Food'), ('CUISINE', 'Cuisine'), ('PLACE_TYPE', 'Place type'), ('PROGRAM', 'Study program'), ('AMENITY', 'Amenity'), ('TIME_OF_DAY', 'Time of day')], db_index=True, max_length=20)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('icon', models.CharField(blank=True, help_text='icon name/emoji for UI', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_user_submitted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Preference categories',
            },
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.PositiveSmallIntegerField(default=5, help_text='1 (mild interest) - 10 (strong preference)')),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_preferences', to='preferences.preferencecategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='preferencecategory',
            index=models.Index(fields=['type', 'is_active'], name='preferences_type_f71001_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='preferencecategory',
            unique_together={('type', 'name')},
        ),
        migrations.AddIndex(
            model_name='userpreference',
            index=models.Index(fields=['user', 'category'], name='preferences_user_id_ce9cdb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userpreference',
            unique_together={('user', 'category')},
        ),
    ]
