# Generated by Django 6.0.6 on 2026-07-06 04:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(help_text='place / fooditem / college', max_length=20)),
                ('object_id', models.PositiveIntegerField()),
                ('score', models.FloatField(help_text='final ranking score at the time of recommendation')),
                ('score_breakdown', models.JSONField(default=dict, help_text='e.g. {preference_match, distance, rating, popularity, time_relevance, review_quality}')),
                ('reason', models.CharField(blank=True, help_text='human-readable reason shown to the user', max_length=255)),
                ('was_clicked', models.BooleanField(default=False)),
                ('was_notified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='search_reco_user_id_bc6d6f_idx'), models.Index(fields=['content_type', 'object_id'], name='search_reco_content_dae8ad_idx')],
            },
        ),
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(db_index=True, max_length=255)),
                ('search_type', models.CharField(choices=[('FOOD', 'Food'), ('PLACE', 'Place'), ('COLLEGE', 'College'), ('GENERAL', 'General')], default='GENERAL', max_length=20)),
                ('city', models.CharField(blank=True, db_index=True, max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('result_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='search_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Search histories',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['query'], name='search_sear_query_d8a8e0_idx'), models.Index(fields=['city', 'created_at'], name='search_sear_city_692e9f_idx')],
            },
        ),
    ]
