# Generated by Django 6.0.6 on 2026-07-06 04:18

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('title', models.CharField(blank=True, max_length=150)),
                ('body', models.TextField(blank=True)),
                ('helpful_count', models.PositiveIntegerField(default=0)),
                ('has_photo', models.BooleanField(default=False)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='review_photos/')),
                ('is_flagged', models.BooleanField(default=False, help_text='reported by users, pending moderation')),
                ('is_approved', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='reviews_rev_content_627d80_idx'), models.Index(fields=['rating'], name='reviews_rev_rating_2db6dd_idx')],
                'unique_together': {('user', 'content_type', 'object_id')},
            },
        ),
    ]
