# Generated by Django 6.0.6 on 2026-07-06 04:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='price snapshot at order time', max_digits=8)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('fulfilment_type', models.CharField(choices=[('DELIVERY', 'Delivery'), ('PICKUP', 'Self pickup')], default='DELIVERY', max_length=10)),
                ('delivery_address', models.CharField(blank=True, max_length=255)),
                ('delivery_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('delivery_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending confirmation'), ('CONFIRMED', 'Confirmed by place'), ('PREPARING', 'Being prepared'), ('OUT_FOR_DELIVERY', 'Out for delivery'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=20)),
                ('special_instructions', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('food_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_requests', to='catalog.fooditem')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_requests', to='catalog.place')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='orders_orde_user_id_021ba7_idx'), models.Index(fields=['place', 'status'], name='orders_orde_place_i_bbba23_idx')],
            },
        ),
    ]
